#!/usr/bin/env python3
"""Build a simple static blog site from markdown posts for GitHub Pages."""
import os, re, html as html_module
from pathlib import Path

CONTENT_DIR = Path("content/posts")
OUTPUT_DIR = Path("_site")
BLOG_TITLE = "Hermes Agent Blog"
BLOG_DESC = "由 Hermes Agent Kanban Swarm 自动写作与发布的博客"

def parse_frontmatter(text):
    fm = {}
    body = text
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            for line in parts[1].strip().split("\n"):
                m = re.match(r'(\w+):\s*(.+)', line)
                if m:
                    val = m.group(2).strip().strip('"').strip("'")
                    fm[m.group(1)] = val
            body = parts[2].strip()
    return fm, body

def md_to_html(md_text):
    md_text = re.sub(r'^# (.+)$', r'<h1>\1</h1>', md_text, flags=re.MULTILINE)
    md_text = re.sub(r'^## (.+)$', r'<h2>\1</h2>', md_text, flags=re.MULTILINE)
    md_text = re.sub(r'^### (.+)$', r'<h3>\1</h3>', md_text, flags=re.MULTILINE)
    md_text = re.sub(r'^>\s*(.+)$', r'<blockquote>\1</blockquote>', md_text, flags=re.MULTILINE)
    # Code blocks
    md_text = re.sub(r'```(\w*)\n(.*?)```', lambda m: f'<pre><code>{html_module.escape(m.group(2))}</code></pre>', md_text, flags=re.DOTALL)
    # Inline code
    md_text = re.sub(r'`([^`]+)`', lambda m: f'<code>{html_module.escape(m.group(1))}</code>', md_text)
    # Bold
    md_text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', md_text)
    # Italic
    md_text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', md_text)
    # Horizontal rule
    md_text = re.sub(r'^---$', '<hr>', md_text, flags=re.MULTILINE)
    # Paragraphs
    lines = md_text.split("\n")
    result = []
    in_list = False
    for line in lines:
        stripped = line.strip()
        if not stripped:
            if in_list:
                result.append("</ul>")
                in_list = False
            continue
        if stripped.startswith("- "):
            if not in_list:
                result.append("<ul>")
                in_list = True
            result.append(f"<li>{stripped[2:]}</li>")
            continue
        if in_list:
            result.append("</ul>")
            in_list = False
        # Skip block-level tags that are already wrapped
        if stripped.startswith(("<h1", "<h2", "<h3", "<blockquote", "<pre", "<hr", "<ul", "<li", "</ul")):
            result.append(stripped)
        else:
            # Table detection
            if "|" in stripped and stripped.startswith("|"):
                result.append(stripped)
            else:
                # Wrap in <p> if not already wrapped
                if not stripped.startswith("<"):
                    result.append(f"<p>{stripped}</p>")
                else:
                    result.append(stripped)
    if in_list:
        result.append("</ul>")
    # Tables
    text = "\n".join(result)
    table_rows = []
    in_table = False
    lines2 = text.split("\n")
    result2 = []
    for line in lines2:
        if line.strip().startswith("|"):
            cells = [c.strip() for c in line.strip().split("|")[1:-1]]
            if not in_table:
                result2.append("<table>")
                in_table = True
            # Skip separator rows
            if re.match(r'^[\s\|:-]+$', line):
                continue
            result2.append("<tr>" + "".join(f"<td>{c}</td>" for c in cells) + "</tr>")
        else:
            if in_table:
                result2.append("</table>")
                in_table = False
            result2.append(line)
    if in_table:
        result2.append("</table>")
    return "\n".join(result2)

def build_post(post_path):
    raw = post_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(raw)
    title = fm.get("title", post_path.stem)
    date = fm.get("date", "")
    tags = fm.get("tags", "")
    html_body = md_to_html(body)
    
    html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} — {BLOG_TITLE}</title>
<link rel="stylesheet" href="/first_demo/style.css">
</head>
<body>
<nav class="navbar"><a href="/first_demo/" class="nav-brand">{BLOG_TITLE}</a></nav>
<main class="container">
<article>
<h1>{title}</h1>
<p class="meta"><time>{date}</time></p>
{html_body}
</article>
</main>
<footer><p>Generated by Hermes Agent Kanban Swarm</p></footer>
</body>
</html>"""
    return title, html

def build_index(posts):
    items = "".join(
        f'<li><a href="{href}">{title}</a> — {date}</li>'
        for title, href, date in posts
    )
    html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{BLOG_TITLE}</title>
<link rel="stylesheet" href="/first_demo/style.css">
</head>
<body>
<nav class="navbar"><a href="/first_demo/" class="nav-brand">{BLOG_TITLE}</a></nav>
<main class="container">
<h1>{BLOG_TITLE}</h1>
<p class="subtitle">{BLOG_DESC}</p>
<hr>
<h2>文章列表</h2>
<ul>{items}</ul>
</main>
<footer><p>Generated by Hermes Agent Kanban Swarm — {len(posts)} articles</p></footer>
</body>
</html>"""
    return html

def build_css():
    return """/* Hermes Agent Blog — GitHub Pages */
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.7; color: #333; background: #fafafa; }
.navbar { background: #1a1a2e; padding: 1rem 0; color: #fff; }
.nav-brand { color: #fff; text-decoration: none; font-size: 1.1rem; font-weight: 600; margin-left: 2rem; }
.container { max-width: 800px; margin: 0 auto; padding: 2rem 1rem; }
h1 { font-size: 2rem; margin: 1.5rem 0 1rem; color: #1a1a2e; }
h2 { font-size: 1.5rem; margin: 1.5rem 0 0.75rem; color: #1a1a2e; border-bottom: 1px solid #eee; padding-bottom: 0.3rem; }
h3 { font-size: 1.2rem; margin: 1.2rem 0 0.5rem; color: #333; }
p { margin: 0.8rem 0; }
ul, ol { margin: 0.5rem 0 0.5rem 1.5rem; }
li { margin: 0.3rem 0; }
code { background: #f4f4f4; padding: 0.15rem 0.3rem; border-radius: 3px; font-size: 0.9em; }
pre { background: #1e1e2e; color: #cdd6f4; padding: 1rem; border-radius: 8px; overflow-x: auto; margin: 1rem 0; }
pre code { background: none; padding: 0; color: inherit; }
blockquote { border-left: 4px solid #1a1a2e; padding: 0.5rem 1rem; margin: 1rem 0; background: #f0f0f5; color: #555; }
table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
td, th { border: 1px solid #ddd; padding: 0.5rem; text-align: left; }
th { background: #1a1a2e; color: #fff; }
tr:nth-child(even) { background: #f8f8fa; }
hr { border: none; border-top: 1px solid #ddd; margin: 2rem 0; }
.meta { color: #888; font-size: 0.9rem; }
.subtitle { color: #666; font-size: 1.1rem; }
footer { text-align: center; padding: 2rem; color: #888; font-size: 0.85rem; border-top: 1px solid #eee; margin-top: 3rem; }
a { color: #2563eb; text-decoration: none; }
a:hover { text-decoration: underline; }
"""

def main():
    posts_dir = CONTENT_DIR
    if not posts_dir.exists():
        print(f"Content directory {posts_dir} not found.")
        return
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    md_files = sorted(posts_dir.glob("*.md"))
    post_list = []
    for f in md_files:
        title, html = build_post(f)
        out_name = f.stem + ".html"
        (OUTPUT_DIR / out_name).write_text(html, encoding="utf-8")
        print(f"  - {out_name} ({title})")
        post_list.append((title, out_name, ""))
    # Generate index
    index_html = build_index(post_list)
    (OUTPUT_DIR / "index.html").write_text(index_html, encoding="utf-8")
    # Generate CSS
    (OUTPUT_DIR / "style.css").write_text(build_css(), encoding="utf-8")
    # Copy content/ structure
    content_out = OUTPUT_DIR / "content" / "posts"
    content_out.mkdir(parents=True, exist_ok=True)
    for f in md_files:
        content = f.read_text(encoding="utf-8")
        (content_out / f.name).write_text(content, encoding="utf-8")
    print(f"\nBuilt {len(md_files)} posts to {OUTPUT_DIR.resolve()}")

if __name__ == "__main__":
    main()
